### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-glass-frogs#1]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
- Create a navbar folder with two files: `navbar.js` and `navbar.scss`
- Inside navbar.js, use bootstrap sticky navbar and add a brand name -- center with bootstrap classes and use Google Font Roboto

**Comment by John-Ryan-Johnson** [comment]
Needs to be sticky/fixed. Bootstrap would be good.

**Comment by isischristopher** [comment]
![image](https://user-images.githubusercontent.com/22875681/66880388-4b558f80-ef88-11e9-9f90-9470763635f5.png)
