### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-glass-frogs#17]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `db/messages.js`
**And** when they add messages it should add them to the list

## Dev Notes
- Create a folder called displayMessage with two files: `displayMessage.js` and `displayMessage.scss` inside of `javascripts/components`
- Create a function called `displayMessageCard` that prints a bootstrap card to the DOM with the message information on the card -- import `printToDom` from `utilities.js` to call in the function

**Comment by isischristopher** [comment]
https://www.w3schools.com/howto/howto_css_chat.asp

**Comment by John-Ryan-Johnson** [comment]
The size of each one may need to be smaller. We have to fit 20 on the page. Easily done in css I believe.
